### ISSUE TITLE
Uvoz

### ISSUE THREAD

**Issue by katarinabrilej** [CebuljIza/APPR-2020-21#2]
Knjižnice, ki jih potrebuješ za uvoz in jih imaš napisane na začetku datoteke `uvoz1.r` raje premakni v datoteko `libraries.r` v mapi `lib` (in tudi vse nadaljne knjižnice, ki jih boš potrebovala za vizualizacijo, analizo, ...). Tako pred začetkom dela samo poženeš to datoteko.

Pri imenih stolpcev pa se raje izogibaj presledkov, npr. `Stevilo_smrti` namesto `Stevilo smrti`.

**Comment by izazupan** [comment]
Hvala za opozorilo, sem popravila.
