### ISSUE TITLE
Težave z Binderjem

### ISSUE THREAD

**Issue by izazupan** [CebuljIza/APPR-2020-21#4]
Imam težave pri odpiranju dokumenta z Binderjem. Če odprem direktno Shiny se mi pokaže error, če pa dokument odprem prek RStudia, mi napiše, da je error pri knjižnici doBy. Če jo ročno ponovno namestim, pa se dokument zažene, a se potem kar samodejno zapre.

**Comment by katarinabrilej** [comment]
Ko sem poročilo odprla v Rstudiu se mi je lepo prevedlo, edino veliko časa rabi. Pri odpiranju Shiny v Binderju je težava najbrž ta, da v naprej pripravljeni sliki za Binder ni paketa `doBy`. To lahko popraviš na način kot je opisano na dnu datoteke `README.md`. Lahko pa namesto funkcije `which.maxn` uporabiš spodnje in ne boš potrebovala paketa `doBy`

```
tabela3 <- leto2000 %>% arrange(desc(Stevilo)) %>% slice(1:5)
```
In podobne za ostalo kjer uporabljaš funkcijo  `which.maxn` .

Še to.
Pri uvozu lahko krajše zapišeš imena stolpcev kot (ni potrebno vsako leto posebej našteti):
```
st.hdi <- c("HDI Rank (2018)", "Drzava", 1990:2018)
```
Enako pri `st.ei`, `st.lei`, ...

**Comment by jaanos** [comment]
Sem dal delat novo sliko, ki bo vključevala paket `doBy` (jaanos/APPR-docker@e46c83725159f0d66b1c29dbf5491083ad309eb0). Vseeno pa svetujem, da narediš tako, kot je predlagala @katarinabrilej. Lahko pa uporabiš tudi funkcijo `slice_min`, ki vrne želeno število vrstic glede na najmanjšo vrednost podanih stolpcev.

**Comment by izazupan** [comment]
Hvala za pomoč, sedaj deluje po pričakovanjih.
