### ISSUE TITLE
Še nekaj vprašanj pred zaključkom

### ISSUE THREAD

**Issue by izazupan** [CebuljIza/APPR-2020-21#5]
1. Ali bi bilo morda pri linearni regresiji (datoteka analiza.r) bolje narediti napoved za manj let (samo do 2021, ker do 2025 mogoče ni realno)? 
2. Kako pri aplikaciji Shiny naredim, da bo y os vedno enaka - da bo prikazovala vrednosti od 0 do 1 - in se ne bo samodejno prilagajala vrednostim ene države? (to je pravzaprav le lepotno)
3. Ali sem dovolj skrajšala poročilo, ali dam ven še kaj? Se mogoče zato tako počasi odpira, ker je prevelika datoteka?

Hvala za pomoč, tudi vsi dodatni komentarji so dobrodošli.

**Comment by katarinabrilej** [comment]
1. Se mi zdi ok do leta 2025, glede na to, da imaš podatke za veliko let nazaj. Morda bi bilo edino boljše, če bi prilagodila kar premico in ne parabole, saj ni preveč smiseln padajoč trend, ki ga parabola napove, glede na to da smo v prejšnjih letih opazili rast. Razen seveda, če je v ozadju nek poseben razlog, da se ti podatki prilegajo ravno kvadratni funkciji. 

2. y os bo vedno enaka, če nastaviš parameter ylim, ko rišeš graf. Torej `... + ylim(0, zgornja meja)`. Zgornjo mejo poračunaš kot največjo vrednost po vseh državah. Morda je to lahko problematično, če so precejšnje razlike v številkah in potem pri državah z majhnimi vrednostmi ne bo dobro videti. 

3. Poročilo se mi zdi ustrezno dolgo. Bi bilo pa nekoliko bolj usklajeno, če bi bili tudi v legendi šumniki in države v slovenščini. In pa tudi, da spremenljivke v legendah nimajo podčrtajev, torej npr. indeks COVID namest indeks_COVID, kot je spremenljivka poimenovana v tabeli. Enako velja za tekst, ki se pojavi, ko se z miško pomakneš nad graf. 

Odpira se res malo dlje, vendar mi vseeno dokaj hitro odpre, najbrž porabi nekaj dlje časa, saj mora zemljevid uvoziti iz interneta (saj se recimo vizualizacija uvaža nekoliko dlje).

**Comment by izazupan** [comment]
Hvala za pomoč. 
Mislim, da sem sedaj z delom zaključila in nalogo lahko oddam.
Ali za to odprem nov issue?

**Comment by jaanos** [comment]
@CebuljIza, ni potrebno odpreti novega issueja - glede na to, da projekt deluje, bom dodal povezavo na repozitorij za zagovore, tako da se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjala, mi javi, da posodobim povezavo.

Svetoval bi le še, da poskrbiš za lep izgled legend pri grafih - te naj imajo lepo berljive naslove (s šumniki, npr. *Država*) in imena posameznih elementov.
